name: Timeout minutes
on: workflow_dispatch
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: echo a string
        run: echo "Hello world!"
        timeout-minutes: 20
        continue-on-error: true
      - name: multiline script
        run: |
          node -v
          npm -v
